default: &default
  adapter: postgresql
  encoding: unicode
  username: pokemon_trainee_app
  password: <%= ENV['PASSWORD'] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV['DB_HOST'] %>
  timeout: 5000

development:
  <<: *default
  database: pokemon_trainee_app_development

test:
  <<: *default
  database: pokemon_trainee_app_test

production:
  <<: *default
  database: pokemon_trainee_app_production
